Feature: Property-based equivalence between SIMD tiers and Portable tier
  As a contributor developing SIMD-accelerated paths
  I want every SIMD tier to produce byte-identical output to the Portable tier
  So that hardware-specific optimizations never silently alter correctness

  Background:
    Given substrate is built with the Cargo feature combination under test
    And the proptest corpus generator is seeded with a fixed seed for reproducibility

  Scenario: BLAKE3 hash of a 1 MiB random input yields byte-identical digest across avx2, neon, and portable tiers
    Given a randomly generated input buffer of exactly 1 MiB
    When the BLAKE3 hash is computed using the avx2 backend
    And the BLAKE3 hash is also computed using the portable backend
    Then the 32-byte hex digest produced by avx2 equals the digest produced by portable
    And when the BLAKE3 hash is computed using the neon backend on an aarch64 host
    Then the 32-byte hex digest produced by neon also equals the digest produced by portable

  Scenario: simdutf8 validation produces the same valid or invalid verdict as std str from_utf8 for a corpus of 1000 random inputs
    Given a corpus of 1000 randomly generated byte strings of length 0 to 65536
    When each byte string is validated using simdutf8::basic::from_utf8
    And each byte string is also validated using std::str::from_utf8
    Then for every input the simdutf8 result is Ok if and only if the std result is Ok
    And for every invalid input the byte offset reported by simdutf8 matches the byte offset reported by std

  Scenario: bytecount newline-count matches a portable counter for inputs from 0 bytes to 10 MiB
    Given a randomly generated input buffer of length drawn uniformly from 0 bytes to 10485760 bytes
    When the number of 0x0A bytes is counted using the bytecount crate with SIMD dispatch
    And the number of 0x0A bytes is counted using a portable scalar loop
    Then the count produced by bytecount equals the count produced by the scalar loop for every input length
